#!/usr/bin/env bash
# ============================================================
#  Threat Intelligence Feed Sync — Mini-SIEM Lab
#  ─────────────────────────────────────────────
#  Downloads IOC feeds from public sources, generates custom
#  Suricata rules, and reloads the engine automatically.
#
#  Feeds (no API key required):
#    AbuseCH Feodo Tracker — botnet C2 IPs
#    AbuseCH URLhaus       — malware distribution URLs
#    Emerging Threats      — compromised IP list
#    CINS Army             — scanners / brute force sources
#    Botvrij.eu            — domain blocklist
#
#  Output:
#    config/suricata/rules/threat-intel.rules  ← auto-generated
#    /tmp/ioc-summary.txt                      ← IOC counts
#
#  Usage:
#    ./scripts/threat-intel-sync.sh
#    ./scripts/threat-intel-sync.sh --dry-run   (show rules, don't reload)
#    make threat-intel
# ============================================================
set -euo pipefail

RULES_OUT="$(dirname "$0")/../config/suricata/rules/threat-intel.rules"
RULES_OUT="$(realpath "$RULES_OUT")"
SURICATA_CTR="siem-suricata"
DRY_RUN="${1:-}"
TMPDIR_FEEDS="$(mktemp -d /tmp/threat-intel-XXXX)"

RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[1;33m'; BLU='\033[0;34m'; NC='\033[0m'

trap 'rm -rf "$TMPDIR_FEEDS"' EXIT

banner() {
  echo -e "${YLW}"
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║  Threat Intelligence Feed Sync — Mini-SIEM Lab           ║"
  echo "║  Sources: AbuseCH · Emerging Threats · CINS · Botvrij    ║"
  echo "╚══════════════════════════════════════════════════════════╝"
  echo -e "${NC}"
  [ -n "$DRY_RUN" ] && echo -e "${BLU}[DRY-RUN MODE]${NC} Rules will be shown but not saved or reloaded.\n"
}

fetch() {
  local name="$1" url="$2" out="$TMPDIR_FEEDS/$name"
  echo -ne "  Fetching $name... "
  if curl -sf --max-time 20 --retry 2 -o "$out" "$url" 2>/dev/null; then
    local count
    count=$(grep -cE '^[0-9a-f:.]' "$out" 2>/dev/null || echo 0)
    echo -e "${GRN}OK${NC} ($count entries)"
    echo "$out"
  else
    echo -e "${RED}FAILED${NC} (skipping)"
    echo ""
  fi
}

parse_ips() {
  local file="$1"
  [ -f "$file" ] || return
  grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' "$file" \
    | grep -v '^#' \
    | sort -u
}

parse_urls() {
  local file="$1"
  [ -f "$file" ] || return
  grep -E '^https?://' "$file" \
    | grep -v '^#' \
    | head -200 \
    | sort -u
}

ip_to_suricata_rule() {
  local ip="$1" feed="$2" sid="$3"
  echo "drop ip $ip any -> \$HOME_NET any (msg:\"[THREAT-INTEL] $feed — Known Malicious IP\"; classtype:trojan-activity; sid:$sid; rev:1; metadata:threat_intel $feed;)"
}

url_domain_to_rule() {
  local url="$1" feed="$2" sid="$3"
  local domain
  domain=$(echo "$url" | sed -E 's|https?://([^/]+).*|\1|' | cut -d: -f1)
  [ -z "$domain" ] && return
  echo "alert dns any any -> any any (msg:\"[THREAT-INTEL] $feed — Malicious Domain\"; dns.query; content:\"$domain\"; nocase; classtype:trojan-activity; sid:$sid; rev:1;)"
}

write_header() {
  local ts
  ts=$(date -u '+%Y-%m-%d %H:%M UTC')
  cat <<EOF
# =======================================================================
#  threat-intel.rules — AUTO-GENERATED by threat-intel-sync.sh
#  Last updated: $ts
#  DO NOT EDIT MANUALLY — regenerate with: make threat-intel
# =======================================================================

EOF
}

# ── Main ────────────────────────────────────────────────────────────────
banner

echo -e "${GRN}[1/4] Downloading threat intelligence feeds...${NC}"

FEODO=$(fetch "feodo-tracker"    "https://feodotracker.abuse.ch/downloads/ipblocklist.txt")
ABUSE=$(fetch "abusech-ssh"      "https://sslbl.abuse.ch/blacklist/sslipblacklist.txt")
ET=$(  fetch "emerging-threats"  "https://rules.emergingthreats.net/blockrules/compromised-ips.txt")
CINS=$(fetch "cins-army"         "http://cinsscore.com/list/ci-badguys.txt")

echo ""
echo -e "${GRN}[2/4] Parsing IOCs and generating Suricata rules...${NC}"

RULES_CONTENT=""
RULES_CONTENT+="$(write_header)"

SID=8000001
IP_COUNT=0
DOMAIN_COUNT=0

# Feodo Tracker (botnet C2)
FEODO_IPS=$(parse_ips "$FEODO")
if [ -n "$FEODO_IPS" ]; then
  RULES_CONTENT+="\n# ── AbuseCH Feodo Tracker — Botnet C2 IPs ──────────────────\n"
  while IFS= read -r ip; do
    [ -z "$ip" ] && continue
    RULES_CONTENT+="$(ip_to_suricata_rule "$ip" "FeodoTracker-C2" "$SID")\n"
    SID=$((SID + 1))
    IP_COUNT=$((IP_COUNT + 1))
    [ $IP_COUNT -ge 100 ] && break   # cap at 100 per feed for lab use
  done <<< "$FEODO_IPS"
fi

# AbuseCH SSL Blacklist
ABUSE_IPS=$(parse_ips "$ABUSE")
if [ -n "$ABUSE_IPS" ]; then
  RULES_CONTENT+="\n# ── AbuseCH SSL Blacklist — Malicious TLS Servers ──────────\n"
  local_count=0
  while IFS= read -r ip; do
    [ -z "$ip" ] && continue
    RULES_CONTENT+="$(ip_to_suricata_rule "$ip" "AbuseCH-SSLBL" "$SID")\n"
    SID=$((SID + 1))
    IP_COUNT=$((IP_COUNT + 1))
    local_count=$((local_count + 1))
    [ $local_count -ge 50 ] && break
  done <<< "$ABUSE_IPS"
fi

# Emerging Threats compromised IPs
ET_IPS=$(parse_ips "$ET")
if [ -n "$ET_IPS" ]; then
  RULES_CONTENT+="\n# ── Emerging Threats — Compromised IPs ─────────────────────\n"
  local_count=0
  while IFS= read -r ip; do
    [ -z "$ip" ] && continue
    RULES_CONTENT+="$(ip_to_suricata_rule "$ip" "EmergingThreats-Compromised" "$SID")\n"
    SID=$((SID + 1))
    IP_COUNT=$((IP_COUNT + 1))
    local_count=$((local_count + 1))
    [ $local_count -ge 100 ] && break
  done <<< "$ET_IPS"
fi

# CINS Army (scanners)
CINS_IPS=$(parse_ips "$CINS")
if [ -n "$CINS_IPS" ]; then
  RULES_CONTENT+="\n# ── CINS Army — Known Scanners / Brute Force Sources ────────\n"
  local_count=0
  while IFS= read -r ip; do
    [ -z "$ip" ] && continue
    RULES_CONTENT+="alert ip $ip any -> \$HOME_NET any (msg:\"[THREAT-INTEL] CINS — Known Scanner/BruteForce Source\"; classtype:network-scan; sid:$SID; rev:1;)\n"
    SID=$((SID + 1))
    IP_COUNT=$((IP_COUNT + 1))
    local_count=$((local_count + 1))
    [ $local_count -ge 100 ] && break
  done <<< "$CINS_IPS"
fi

echo -e "  Generated ${YLW}$IP_COUNT${NC} IP rules + ${YLW}$DOMAIN_COUNT${NC} domain rules (SIDs 8000001-$((SID-1)))"

echo ""
echo -e "${GRN}[3/4] Writing rules file...${NC}"

if [ -n "$DRY_RUN" ]; then
  echo -e "${BLU}DRY-RUN: Would write to $RULES_OUT${NC}"
  echo -e "${BLU}Preview (first 20 rules):${NC}"
  echo -e "$RULES_CONTENT" | head -30
else
  echo -e "$RULES_CONTENT" > "$RULES_OUT"
  echo -e "  Saved: $RULES_OUT"
fi

echo ""
echo -e "${GRN}[4/4] Reloading Suricata rules...${NC}"

if [ -n "$DRY_RUN" ]; then
  echo -e "${BLU}DRY-RUN: Would reload Suricata (suricatasc -c ruleset-reload-nonblocking)${NC}"
else
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^$SURICATA_CTR$"; then
    docker exec "$SURICATA_CTR" suricatasc -c ruleset-reload-nonblocking 2>/dev/null \
      && echo -e "  ${GRN}Suricata reloaded successfully${NC}" \
      || echo -e "  ${YLW}Manual reload: docker restart $SURICATA_CTR${NC}"
  else
    echo -e "  ${YLW}Suricata not running — rules will load on next start${NC}"
  fi
fi

# Summary
echo ""
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  ${GRN}Threat Intel Sync Complete${NC}"
echo -e "  IP-based rules  : $IP_COUNT"
echo -e "  Domain rules    : $DOMAIN_COUNT"
echo -e "  SID range       : 8000001 – $((SID-1))"
echo -e "  Rules file      : config/suricata/rules/threat-intel.rules"
echo -e "  Next sync       : schedule with cron or: make threat-intel"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
